name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build ./website --file ./website/Dockerfile --tag hamedo1/gr-website:latest

    - name: Run Docker Container
      run: docker run -d -p 8080:80 your-image-name


